site_name: TestPlan Documentation

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  language: es
  features:
    - navigation.instant
    - search.highlight
    - search.share

nav:
  - Inicio: index.md
  - Criterios de Aceptación (S0): criterios_sprint0.md

plugins:
  - search